# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7068a662a5203e01e168072c4829b45c7f798ccadb1b64156fd5f4f521ae4e5e466651e60ec8cd37eb7887577101b62686d4edd2f929c410ee51bceb3f86ae3

test:
  secret_key_base: 8a59e8e5a8b62b1074d13dea6b0381d9a75ca58302d339e4748d7334c2d6c09a3ca6134f2b21a16a5f03827e1d47e0217aab61adca0f6471819272c3179b0eac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
